version: "3.8"
services:
  api_test:
    build: $PWD/api
    volumes:
      - $PWD/api/app:/app
    ports:
      - "28088:5000"
    environment:
      - FLASK_ENV
      - DEBUG
      - JWT_ISSUER
      - JWT_SECRET
      - SRS_DB_HOST
      - SRS_DB_PORT
      - POSTGRES_PASSWORD
      - SRS_DB
      - SRS_USER
      - SRS_PASSWORD
      - TEST_HOST
      - TEST_PORT
      - TEST


    restart: unless-stopped

    depends_on:
      - db
    command:  ["flask", "run", "--host=0.0.0.0"]

  db:
    build: $PWD/db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD
      - SRS_DB
      - SRS_USER
      - SRS_PASSWORD
    restart: unless-stopped
  db-admin:
    image: adminer
    ports:
      - 8081:8080
    restart: unless-stopped
    depends_on:
      - db

volumes:
  db_data: