#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $SRS_USER WITH PASSWORD '$SRS_PASSWORD';
    CREATE DATABASE $SRS_DB;
    GRANT ALL PRIVILEGES ON DATABASE $SRS_DB TO $SRS_USER;
EOSQL

# SRS_TEST_DB='SRS_test'
# SRS_TEST_USER='SRS_test'
# SRS_TEST_PASSWORD='SRS_test'

# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
#     CREATE USER $SRS_TEST_USER WITH PASSWORD '$SRS_TEST_PASSWORD';
#     CREATE DATABASE $SRS_TEST_DB;
#     GRANT ALL PRIVILEGES ON DATABASE $SRS_TEST_DB TO $SRS_TEST_USER;
# EOSQL
